/* eslint-disable import/prefer-default-export */

export const SHOW_GRAPH_ACTION_WINDOW = 'SHOW_GRAPH_ACTION_WINDOW'
export const ADD_GRAPH_CONFIG = 'ADD_GRAPH_CONFIG'
export const TOGGLE_GRAPH_DRAGGING = 'TOGGLE_GRAPH_DRAGGING'
export const DATA_REQUEST_STARTED = 'DATA_REQUEST_STARTED'
export const DATA_RECIEVE_SUCCESS = 'DATA_RECIEVE_SUCCESS'
export const DATA_RECIEVE_FAILURE = 'DATA_RECIEVE_FAILURE'
