version: "2"

services:
  mainflux-interface:
    container_name: mainflux_interface
    restart: on-failure
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    links:
      - mainflux-api
    networks:
      - mainflux-base-net

  mainflux-api:
    container_name: mainflux_api
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./mainflux_api:/mainflux_api
    depends_on:
      - mainflux-db
    links:
      - mainflux-db
    networks:
      - mainflux-base-net
    environment:
      WAIT_HOSTS: mongodb:27017
      DATABASE_URL: mongodb://mainflux-db:27017/mainflux_admin
      # Write down relevant bootstrap and mainflux urls
      MAINFLUX_URL: 134.209.240.215
      BOOTSTRAP_URL: 134.209.240.215:8200
      UI_URL: http://localhost:8000

  mainflux-db:
    container_name: mainflux_db
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    command: mongod
    networks:
      - mainflux-base-net

networks:
  mainflux-base-net:
    driver: bridge

volumes:
  mongo_data:


